# Generated by Django 5.2.7 on 2025-10-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        help_text="место, в котором необходимо выполнять привычку",
                        max_length=500,
                        verbose_name="Место",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        help_text="время, когда необходимо выполнять привычку",
                        verbose_name="Время",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="действие, которое представляет собой привычка",
                        max_length=500,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "a_sign_of_a_pleasant_habit",
                    models.BooleanField(
                        default=False,
                        help_text="привычка, которую можно привязать к выполнению полезной привычки",
                        verbose_name="Это приятная привычка?",
                    ),
                ),
                (
                    "associated_habit",
                    models.CharField(
                        blank=True,
                        help_text="укажите приятную привычку",
                        max_length=500,
                        null=True,
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="периодичность выполнения привычки для напоминания в днях",
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "reward",
                    models.TextField(
                        blank=True,
                        help_text="введите то, что вы хотели бы получить в виде вознаграждения",
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "time_to_complete",
                    models.PositiveIntegerField(
                        help_text="предположительное время, которое вы потратите на выполение привычки",
                        verbose_name="Время на выполнение",
                    ),
                ),
                (
                    "publication_sign",
                    models.BooleanField(
                        default=False,
                        help_text="опубликовать?",
                        verbose_name="Признак публичности",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
