# Generated by Django 5.2.7 on 2025-10-26 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="associated_habit",
            field=models.ForeignKey(
                blank=True,
                help_text="укажите приятную привычку",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="habits.habit",
                verbose_name="Связанная привычка",
            ),
        ),
    ]
