# Generated by Django 5.2.7 on 2025-10-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habit_associated_habit"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="chat_id",
            field=models.IntegerField(
                blank=True,
                help_text="Это нужно для работоспособности отправки уведомлений. Получить его можно перейдя в бота @userinfobot и отправив /start",
                null=True,
                verbose_name="Впишите свой chat_id телеграмма",
            ),
        ),
    ]
