# Generated by Django 5.2.7 on 2025-10-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_habit_chat_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="chat_id",
            field=models.CharField(
                blank=True,
                help_text="Это нужно для работоспособности отправки уведомлений. Получить его можно перейдя в бота @userinfobot и отправив /start",
                max_length=10,
                null=True,
                verbose_name="Впишите свой chat_id телеграмма",
            ),
        ),
    ]
